# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BioPhysCode
#email: biophyscode@gmail.com
description: >
  Web portal for the biophyscode project.
#---baseurl is the subpath of your site, e.g. /blog
baseurl: "/bpc"
github_username:  bradleyrp
highlighter: rouge

#---build settings
markdown: kramdown
collections:
  posts:
    output: true
    permalink: /posts/:path.html
  articles:
    output: true
    permalink: /articles/:title.html
  test_reports:
    output: true
    permalink: /test_reports/:title.html
